name: Update References

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  update-references:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Update references.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "
import base64
from github import Github

token = '${{ secrets.GITHUB_TOKEN }}'
repo_name = 'MarcosGiannini/MarcosGiannini.github.io'
file_path = 'references.md'

# Conectar al repositorio
g = Github(token)
repo = g.get_repo(repo_name)

# Obtener contenido del archivo actual
file_content = repo.get_contents(file_path)
new_content = file_content.decoded_content.decode() + '\\n\\n# Test update\\nThis is a test update from GitHub Actions.'
repo.update_file(file_path, 'Automated update to references.md', new_content, file_content.sha)
print('File updated successfully!')
        " > script.py
        python script.py
