name: Update References

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  update-references:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Update references.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'import base64' > script.py
        echo 'from github import Github' >> script.py
        echo 'token = "${{ secrets.GITHUB_TOKEN }}"' >> script.py
        echo 'repo_name = "MarcosGiannini/MarcosGiannini.github.io"' >> script.py
        echo 'file_path = "references.md"' >> script.py
        echo 'g = Github(token)' >> script.py
        echo 'repo = g.get_repo(repo_name)' >> script.py
        echo 'file_content = repo.get_contents(file_path)' >> script.py
        echo 'new_content = file_content.decoded_content.decode() + "\\n\\n# Test update\\nThis is a test update from GitHub Actions."' >> script.py
        echo 'repo.update_file(file_path, "Automated update to references.md", new_content, file_content.sha)' >> script.py
        echo 'print("File updated successfully!")' >> script.py
        python script.py
